### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by H-Liu1997** [PKUFlyingPig/Princeton-Algorithm#1]
你好~
很抱歉来这打扰啦，我最近也在复现https://github.com/simonalexanderson/StyleGestures，
看见了你和作者的讨论，
想问下你在自己数据集训练，有遇到生成的结果抖动的很厉害的情况嘛，结果平滑吗？

非常感谢~~~

**Comment by PKUFlyingPig** [comment]
是有抖动的情况，印象中用他训练集做归一化就不会剧烈抖动，但是感觉手部还是偶尔会有转动。

**Comment by H-Liu1997** [comment]
感谢回复！

不知道能给你发个视频客观描述下抖动程度嘛。

我自己的数据集1900个training
samples，炼了快400个epoch还是全身都抖，我今天简单的把bvh和audio路径替换成我的。没有动其他地方。

另外你的意思是你自己的数据集也抖得很厉害，他的数据集，稍微好一些，手部偶尔抖嘛。

我在想是不是数据集大小的原因




PKUFlyingPig <notifications@github.com>于2021年3月11日 周四00:54写道：

**Comment by H-Liu1997** [comment]
感谢回复，
已解决，更多的iterations 会基本消除抖动。
谢啦
